### ISSUE TITLE
[Feature Request] Allow copying and forwarding restricted content

### ISSUE THREAD

**Issue by thisago** [23rd/tdesktop#100]
### Is your feature request related to a problem?

The restricted content chats blocks you to copy and forward text even for admins! very anooying

### Describe the solution you'd like

Just allow copy and forwarding in all chats

### Describe alternatives you've considered

remove the restricted chat verification for copy

### Additional context

IDK if it is too simple, but it will be very good if the copy (and forward) was enabled

**Comment by 23rd** [comment]
Feel free to make your own versions with any changes that can possibly violate Telegram's ToS, I won't.

**Comment by thisago** [comment]
>can possibly violate Telegram's ToS

I didn't know that this violate the terms, thanks
