### ISSUE TITLE
Corrupted 4.7 release archive

### ISSUE THREAD

**Issue by Anidetrix** [23rd/tdesktop#101]
### Steps to reproduce

1. Download archive
2. Try to open it either using 7-Zip or built-in Windows utility

### Expected behaviour

Archive opens

### Actual behaviour

![image](https://user-images.githubusercontent.com/11345792/226551038-5aa7046f-0767-47aa-9e68-5e30786c85a8.png)
![image](https://user-images.githubusercontent.com/11345792/226551112-6dc570dc-6d04-4ab6-944a-49077038f5af.png)

### Operating system

Windows 11

### Version of Telegram Desktop

4.7

### Installation source

Static binary from official website

**Comment by D2** [comment]
I'd like to add that trying to update to the lastest version with the inbuilt utility causes a memory leak and corrupts your tdata folder

**Comment by 23rd** [comment]
My bad, thanks for your report. Now it should be better.

**Comment by J4CKED** [comment]
Working. Thank you.
