### ISSUE TITLE
Forkgram window always on top pin button not clickable on Windows 11

### ISSUE THREAD

**Issue by damienleger** [23rd/tdesktop#104]
### Steps to reproduce

Run a fresh Windows 11 install.
Just run Forkgram on Window 11. Notice that the window always on top pin button doesn't work neither by having mouse over or clicking on it (nothing happen).

### Expected behaviour

To work just like on Windows 10

### Actual behaviour

Button is not clickable and does nothing

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.1 x64

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Should be better now.

**Comment by damienleger** [comment]
Indeed it's working in 4.9.4 x64 thanks!
