### ISSUE TITLE
Option to toggle "all recent stickers" option is missing

### ISSUE THREAD

**Issue by biscober** [23rd/tdesktop#107]
### Steps to reproduce

1. Open Fork Settings
2. Observe there is no option to toggle the state of the "all recent stickers" feature

The option appears to have been removed from the settings_fork.cpp file in the "Updated to 2.4." commit here: https://github.com/telegramdesktop/tdesktop/commit/eaec931512c961f7e0c18db62d0f4fa99b24caef and does not appear to have been re-added since.

### Expected behaviour

Option to toggle the "all recent stickers" feature off / on would be present in Fork Settings.
On = Unlimited amount of recent stickers (which appears to be the Forkgram default behavior, and my personal preference)
Off = Showing the Telegram default of 20 stickers maximum under recent stickers

### Actual behaviour

Option to toggle the "all recent stickers" feature on / off is not present in Fork Settings

### Operating system

Windows 11

### Version of Telegram Desktop

4.10.2

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
After the Premium feature this option has no sense.

https://github.com/forkgram/tdesktop/issues/90#issuecomment-1382496087
