### ISSUE TITLE
Please update to 4.10.3 : External link opening crashing in Linux

### ISSUE THREAD

**Issue by athuld** [23rd/tdesktop#108]
### Steps to reproduce

Opening external link crashes the client

### Expected behaviour

Client doesn't crash :)

### Actual behaviour

Crashes the client. This is fixed from telegram's side on 4.10.3

### Operating system

Linux

### Version of Telegram Desktop

4.10.2

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Should be better now.
