### ISSUE TITLE
App not starts

### ISSUE THREAD

**Issue by DMyachin** [23rd/tdesktop#112]
### Steps to reproduce

1. Update to last version from Arch's AUR
2. Try to launch

`Forkgram: error while loading shared libraries: libprotobuf-lite.so.24: cannot open shared object file: No such file or directory`

```
➜  ~ ll /usr/lib/libprotobuf-lite*
lrwxrwxrwx 1 root root   22 ноя  4 22:38 /usr/lib/libprotobuf-lite.so -> libprotobuf-lite.so.25
lrwxrwxrwx 1 root root   26 ноя  4 22:38 /usr/lib/libprotobuf-lite.so.25 -> libprotobuf-lite.so.25.0.0
-rwxr-xr-x 1 root root 747K ноя  4 22:38 /usr/lib/libprotobuf-lite.so.25.0.0
➜  ~ 
```

### Operating system

Arch Linux

### Version of Telegram Desktop

forkgram 4.11.3

### Installation source

AUR

**Comment by 23rd** [comment]
Binaries for Arch Linux are not built by me.
