### ISSUE TITLE
Remember Photo is wrong Font Size

### ISSUE THREAD

**Issue by miranyx** [23rd/tdesktop#116]
### Steps to reproduce

1. Get A picture sent to you
2. Right Click it

### Expected behaviour

Every menu Point in the Right click context menu is the same font and same margin away from the border.

### Actual behaviour

Remember Photo is smaller and on the left border touching it.
<img width="198" alt="Screenshot 2023-11-29 at 14 57 08" src="https://github.com/forkgram/tdesktop/assets/64905406/c6576f9d-0167-47ab-9ebb-405e9c3a4e63">

### Operating system

Macos 14.1

### Version of Telegram Desktop

4.11.7

### Installation source

Other (unofficial) source

**Comment by 23rd** [comment]
Intended.
