### ISSUE TITLE
Export Contatcs with IDs included

### ISSUE THREAD

**Issue by HolyMoly81** [23rd/tdesktop#118]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

When exporting contacts only name and number will be exported, not the ID. So There will be no chance to find back the User when only connectied via Telegram without sharing phonenumber. Therefore the ID would be nice to at least compare later if its the same User.
So exportin a list of contacts as csv for example with name, number and id would be awesome i think

### Describe alternatives you've considered

Create a nice csv with all the data

**Comment by 23rd** [comment]
Advanced — Experimental settings — Turn on IDs in Profile.
