### ISSUE TITLE
Wrong folder message counter

### ISSUE THREAD

**Issue by liponex** [23rd/tdesktop#128]
### Steps to reproduce

Forkgram from GitHub releases
1. Create folder, for only new messages (exclude already read chats)
2. Get some new messages
3. Read them
4. Message counter will not go down
![изображение](https://github.com/forkgram/tdesktop/assets/43170114/1a2b4c03-2bdf-4388-90d2-bff986180407)
![изображение](https://github.com/forkgram/tdesktop/assets/43170114/176cbd3e-e4fe-4bc9-a9a3-89f4343697a5)

### Expected behaviour

Message counter of the folder with new messages must go down, after messages were read.

### Actual behaviour

Counter is getting number with this pattern: number of messages came - number of channels/groups/chats. And counter adds every time.

### Operating system

Windows 10

### Version of Telegram Desktop

Forkgram v5.0 x64

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Is the problem repeated in the official version of the client?

**Comment by liponex** [comment]
@23rd No, it's not. Forgot to close this issue.
