### ISSUE TITLE
Picture can't scale using "Ctrl"+“Mouse wheel” 

### ISSUE THREAD

**Issue by zengjiapei3000** [23rd/tdesktop#129]
### Steps to reproduce

This feature that "scaling picture" works on **Telegram Desktop v5.0 x64**, but not works on **Forkgram Desktop v5.0 x64**:
1. open a picture in forkgram;
2. press “Ctrl" and scroll the mouse wheel.

### Expected behaviour

This picture will scale big or small.

### Actual behaviour

None.

### Operating system

Windows 11 Family Chinese 23H2 Operating System Version 22631.3447

### Version of Telegram Desktop

Version 5.0 x64

### Installation source

Other (unofficial) source (scoop, bucket "extras")

**Comment by 23rd** [comment]
Don't touch ctrl button.
