### ISSUE TITLE
[Feature Request] Try to save deleted messages

### ISSUE THREAD

**Issue by zarEclEC** [23rd/tdesktop#13]

**Comment by 23rd** [comment]
I wanted to do this almost 2 years ago, when I just started developing fork.
Now I think that saving deleted messages is cheating and may violates terms of Telegram clients.

**Comment by zarEclEC** [comment]
Yeah, you are right at this. I just copied things without reading. 
Implementing this would lead Telegram team to revoke your api keys

**Comment by Athari** [comment]
Maybe there's a realistic alternative? Like automatic backing up of all messages and files. Immediate or daily. If messages aren't displayed in the UI, but are stored in some HTML/JSON backup, it's fine, right? Users can already do this manually even in the default client, it's just automation.

**Comment by 23rd** [comment]
If you build any (official or not) client in the debug mode, you will get the `DebugLogs` folder, which will have all mtp requests (with text of messages and etc.).
