### ISSUE TITLE
[Feature Request] "ENTER" key on login should go on

### ISSUE THREAD

**Issue by zarEclEC** [23rd/tdesktop#16]
![immagine](https://user-images.githubusercontent.com/6240983/52913865-2823f480-32c2-11e9-82c3-c3b3990f9007.png)

If I press "ENTER" key, it should go on like if I pressed the "START MESSAGING" button

**Comment by 23rd** [comment]
It works as you write. Maybe you just lost focus.

**Comment by zarEclEC** [comment]
I just tried and didn't work, I clicked in the black region, I can do a video

**Comment by 23rd** [comment]
Cant reproduce.
![image](https://user-images.githubusercontent.com/4051126/52914297-b6ef3c00-32d7-11e9-8cd0-21ea197ac085.gif)

**Comment by zarEclEC** [comment]
I just re-tried this, and ENTER worked.

This time I opened another istance with "-many -workdir" arguments, but I remember it didn't work when I logged out and tried to log in, can you test in this case?

**Comment by 23rd** [comment]
Test in official build first.

**Comment by zarEclEC** [comment]
Tested in official, it's not working. Then it's a issue I should have opened in the official repo.
I'm sorry, you are right. I will test things in official first, from now on
