### ISSUE TITLE
[Feature Request] Click to "Emoji" in upper right should go to the top of the emoji panel, if we are already in emoji panel

### ISSUE THREAD

**Issue by zarEclEC** [23rd/tdesktop#20]
[Feature Request] Click to "Emoji" in upper right should go to the top of the emoji panel, if we are already in emoji panel

**Comment by 23rd** [comment]
@ArmeF97 

I'm not sure what you mean by "upper right" but now click on activated tab brings you to top.
I hope that's what you wanted.

3fa3428b4bb6ab88406e468f70b21beaeaa16d1f

**Comment by zarEclEC** [comment]
Exactly this! Thanks!
