### ISSUE TITLE
[Feature Request] Unread messagges filter

### ISSUE THREAD

**Issue by zarEclEC** [23rd/tdesktop#24]
Just like in Unigram when you press F6, only unread chats should display on the left.
The key can be what you want, just let it configurable by settings.
This feature is amazing, it's the only reason I use Unigram. If implemented in forkgram (and one day I hope in telegram), it would increase productivity a lot

**Comment by 23rd** [comment]
Could you please record a video of this feature? This would help me understand the behavior of it much better.
(You can use Imgur to upload a mute mp4.)

**Comment by zarEclEC** [comment]
https://www.youtube.com/watch?v=P7OVKy1nIKA&feature=youtu.be

**Comment by zarEclEC** [comment]
Is it enough to understand? Thanks :D

**Comment by 23rd** [comment]
I think I can close it now. =)

**Comment by zarEclEC** [comment]
Yes, thanks
