### ISSUE TITLE
Wrong version of libssl-dev in GitHub Actions CI

### ISSUE THREAD

**Issue by EricKotato** [23rd/tdesktop#25]
In `ubuntu-16.04` in GitHub Actions CI there is a preinstalled OpenSSL 1.1.1:
```
libssl-dev is already the newest version (1.1.1c-1+ubuntu16.04.1+deb.sury.org+1).
```
Because of this Qt 5.6.2 won't build.

The solution is to remove preinstalled `libssl-dev` and reinstall it from `xenial-security`:
```sh
sudo apt-get remove libssl-dev && \
sudo apt-get install -t xenial-security libssl-dev
```

**Comment by 23rd** [comment]
Thanks.
