### ISSUE TITLE
[Feature Request] Add an option to select app icon

### ISSUE THREAD

**Issue by sqliuchang** [23rd/tdesktop#26]
Is there any possibility to add an option to select app icon just like the official ios app?
I have been used to the original icon...

![image_2020-01-08_22-04-53.png](https://i.loli.net/2020/01/08/49rhMca6YKIeqiw.png)

**Comment by 23rd** [comment]
Yes, I can add an icon selection option, but only between the official and the Forkgram's icon.

**Comment by 23rd** [comment]
In the next release, you can combine these two options.

![image](https://user-images.githubusercontent.com/4051126/72138759-8c4e1c00-339e-11ea-9a2c-11a1299d9ef8.png)

**Comment by sqliuchang** [comment]
> In the next release, you can combine these two options.

Thank you !!!
