### ISSUE TITLE
[Feature Request] Is there any possibility to add  linux binaries in release?

### ISSUE THREAD

**Issue by sqliuchang** [23rd/tdesktop#27]
I now often work in Ubuntu 18.04 and find I can't input Chinese in snap store's telegram.
And I can't tolerate those almost half screen stickers in the official app.
So I come here to ask for linux version release.
If not, I will try to build it with github actions and want to know which codes I should modify after I fork this repository.

**Comment by sqliuchang** [comment]
I have successfully compiled it in github actions and it works perfectly in Ubuntu 18.04!

**Comment by 23rd** [comment]
I don't release Linux binaries, but I build them. So if you successfully built a Linux version, you probably will get the auto updates.

**Comment by zarEclEC** [comment]
Can you share just one binary?

**Comment by 23rd** [comment]
Yeah, I had a 1.9.6 binary, so I uploaded it to [corresponding release](https://github.com/Forkgram/tdesktop/releases/tag/v1.9.6).

**Comment by sqliuchang** [comment]
> Can you share just one binary?

You can download the latest version which was compiled yesterday
https://github.com/sqliuchang/tdesktop/actions/runs/50161312

Then you can modify or touch this file
`/home/{#your_user_name}/.local/share/applications/telegramdesktop.desktop`

```
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/sqliuchang/snap/telegram-desktop/Telegram
Exec=/home/sqliuchang/snap/telegram-desktop/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
X-GNOME-UsesNotifications=true
```

**Comment by 23rd** [comment]
@sqliuchang Unfortunately your binary was built with the [Test API ID](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/api_credentials.md) and with the Debug configuration.

**Comment by zarEclEC** [comment]
> So if you successfully built a Linux version, you probably will get the auto updates.

I download the binary you suggested, and it updated to official telegram version :( 
No forkgram for linux

**Comment by 23rd** [comment]
>I download the binary you suggested, and it updated to official telegram version :(
No forkgram for linux

Are you sure about this? I double-checked it and it's properly updated.

**Comment by sqliuchang** [comment]
> Are you sure about this? I double-checked it and it's properly updated.

Yes, I have the same problem yesterday.

It will update to official version if update automatically is enable before I login and it's default enabled. In this case, telegram has downloaded the official update when I login. And it shows "update telegram" in the lower left corner which I have never seen in forkgram.

Then I disable update automatically and move the original forkgram binary back. I can update normally in advanced settings now. I can't explain why but it just works.

By the way, I have never enabled install beta versions, but both windows and linux forkgarm
client will update to 1.9.19 beta.

Sorry for my poor English.

**Comment by 23rd** [comment]
Okay, what about this?

https://github.com/Forkgram/tdesktop/releases/download/v1.9.17/Telegram.tar.xz
