### ISSUE TITLE
[Feature Request] Move settings, translate them

### ISSUE THREAD

**Issue by resistancelion** [23rd/tdesktop#30]
### Is your feature request related to a problem?
It is uncorrect to add settings thumbs in unsuitable settings sections

### Describe the solution you'd like
There are already existant setting categories, which must be suitable for adding settings in them

### Additional context
It would be great to add translation for the settings entries.

**Comment by 23rd** [comment]
No, I'm not going to do that. The fork's settings are in a separate category to make it clear to users what advanced features they have. Spreading settings into existing categories would only confuse users.

> It would be great to add translation for the settings entries.

You can do it yourself by creating your own language pack and add it to the app.
