### ISSUE TITLE
[Question] why not to use .patch instead?

### ISSUE THREAD

**Issue by resistancelion** [23rd/tdesktop#31]
Why not to use .patch files to provide changes instead of copying files from new telegram releases, so, everyone can just download .patch files and apply related patches to the source?

**Comment by 23rd** [comment]
> so, everyone can just download .patch files and apply related patches to the source?

Everyone can "just" clone this repo as well.
Anyway, this could have been done with patch files, if I had decided to do so in the beginning. Now it is too late to change the way this fork is up-to-date.
