### ISSUE TITLE
[Feature Request]  Linux Support

### ISSUE THREAD

**Issue by ruizlenato** [23rd/tdesktop#34]
When will they add support for Linux?

**Comment by yukosky** [comment]
quando eu te comer

**Comment by 23rd** [comment]
https://github.com/Forkgram/tdesktop/releases/download/v1.9.17/Telegram.tar.xz

**Comment by ruizlenato** [comment]
> https://github.com/Forkgram/tdesktop/releases/download/v1.9.17/Telegram.tar.xz

Is that version old?

**Comment by alissonlauffer** [comment]
> https://github.com/Forkgram/tdesktop/releases/download/v1.9.17/Telegram.tar.xz

The auto update feature of this release is downloading the "stock" Telegram Desktop.

**Comment by 23rd** [comment]
> Is that version old?

It will be updated to the latest version.

> The auto update feature of this release is downloading the "stock" Telegram Desktop.

I checked on a fresh virtual machine, the stock version will not be installed.

**Comment by sleeplife** [comment]
why dont you submit forkgram to flatpak (flathub) ?

**Comment by 23rd** [comment]
Unfortunately, I don't have enough time for this. If you want you can help me with that.

**Comment by sleeplife** [comment]
unfortunately I dont know how to do that :(

Let me read flathub documentary or hope someone hear help me

**Comment by 23rd** [comment]
I think it can be closed.
