### ISSUE TITLE
As of 2.4.10 images automatically zoom themselves in when opening; zooming out brings them to a lower zoom level than normal

### ISSUE THREAD

**Issue by sjain882** [23rd/tdesktop#37]
### Steps to reproduce
See video:

https://youtu.be/eURyfpuu2zI

- Watch at low speed.
- At first it opens normally at perfect size like 2.4.8 then zooms in one step by itself.
- Zooming out one level with - brings it to a lower zoom level than the normal zoom level that was visible for a split second at first, its too small. 

I triple checked my keyboard didnt have a stuck key and tried on another device, same issue

### Expected behaviour
Image should open and not zoom in by itself.

### Configuration
**Operating system:** Windows 10 Enterprise x64 2004 built 19041.450

DPI Scaling is on 175%

**Version of Forkgram Desktop:** 2.4.10 latest

**Installation source (Linux Only)** - >>GitHub releases<<

**Comment by 23rd** [comment]
Please check 2.4.11 version.

**Comment by sjain882** [comment]
> Please check 2.4.11 version.

Fixed! It works just like before now. What an unblieveable speed. Thank you so much!!!!
