### ISSUE TITLE
[Feature Request] Allow users to adjust text size and/or set custom interface scaling percentages. 

### ISSUE THREAD

**Issue by incIined** [23rd/tdesktop#39]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.
TDesktop has interface scales at 100%, 125, 200, 250, and 300. For my eyes, 125% makes everything too big but 100% leaves the text a tiny bit too small. 

### Describe the solution you'd like
Add an adjustable slider to let users change the text size, or allow users to set a custom interface scale (for example, 115%). 

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by 23rd** [comment]
Hi.
I did it 1.5 years ago.
Check this commit: 47910b2ae180b6429adafef13ebf97cb75ad9dca.
Example: `Telegram.exe -scale 115`.
