### ISSUE TITLE
[Feature Request] Increse the max account limit (current to 3)

### ISSUE THREAD

**Issue by zarEclEC** [23rd/tdesktop#40]

**Comment by resistancelion** [comment]
> _No description provided._

https://github.com/resistancelion/tdesktop/commit/7b4f4a856555b6399a4776623101da265d63191b

**Comment by resistancelion** [comment]
> _No description provided._

https://github.com/Forkgram/tdesktop/pull/51

**Comment by zarEclEC** [comment]
Nice, hope this get merged soon! 👍
