### ISSUE TITLE
ACCOUNT ID - FORKGRAM DESKTOP - WINDOWS 7_x64

### ISSUE THREAD

**Issue by CoalaDePorsche** [23rd/tdesktop#41]
I'm not able to find the account ID of the profiles I open on ForkGram, on ForkGram Mobile I can see the account ID on the profile, is that a bug?

I'm using ForkGram Desktop

My operating system: Windows 7_x64

**Comment by CoalaDePorsche** [comment]
recorded a video opening the profile in forkgram desktop

my system: windows 7_x64

does not show the account id


https://user-images.githubusercontent.com/68451871/103102640-bc1c2100-45fb-11eb-936a-ff012484b96b.mp4

**Comment by 23rd** [comment]
Should be fixed in 2.9.2.
