### ISSUE TITLE
Forkgram is violating Telegram API Transparency ToS

### ISSUE THREAD

**Issue by Fardin574** [23rd/tdesktop#46]
hey there!
i was chatting with a friend of mine and he mentioned that he's using Forkgram and send me this screenshot

![image](https://user-images.githubusercontent.com/55962072/110669587-b76e0e80-81e1-11eb-9cd9-87206254b0c7.png)

i dig a little more and found this ![image](https://user-images.githubusercontent.com/55962072/110670278-775b5b80-81e2-11eb-9177-51089026e752.png)

that was weird because Forkgram is using the Telegram brand and logo so i download it myself to check it, turns out even on the first page and login menu there is no sign of Forkgram or logo or even mention that this is an "Unofficial" App!
![image](https://user-images.githubusercontent.com/55962072/110672123-87743a80-81e4-11eb-9b90-16e08d123f85.png)

based on Transparency section in [Telegram API ToS](https://core.telegram.org/api/terms):

> 2.2. We offer our API free of charge, but your users must be aware of the fact that your app uses the Telegram API and is part of the Telegram ecosystem. This fact must be featured prominently in the app's description in the app stores and in the in-app intro if your app has it.
2.3. To avoid confusion, the title of your app must not include the word “Telegram”. An exception can be made if the word “Telegram” is preceded with the word “Unofficial” in the title.
2.4. You must not use the official Telegram logo for your app. Both the Telegram brand and its logo are registered trademarks protected by law in almost every country.
 
Forkgram is clearly violating [Telegram API ToS](https://core.telegram.org/api/terms)

**Comment by 23rd** [comment]
Should be better now.

**Comment by Fardin574** [comment]
yeah, looks better
closing this issue
thank you :)
