### ISSUE TITLE
Install official Telegram on auto update

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [23rd/tdesktop#48]
### Steps to reproduce
1. Download the latest Forkgram Linux version. #34 
2. Wait until it updates to the latest version via auto update
3. Restart it.

### Expected behavior
It should update to Forkgram latest version.

### Actual behaviour
It's Telegram desktop official version.

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** According to #34 v1.9.17 on installation. v2.8 on auto update.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Github releases

**Used theme**: I think it does not matter.

![image](https://user-images.githubusercontent.com/17345129/123431802-ecf70600-d5de-11eb-8c17-11087b6001cd.png)

**Comment by 23rd** [comment]
Yeah, I can confirm the problem, sorry for that.
I have added a binary file for Linux systems to the latest release.
