### ISSUE TITLE
URI Scheme doesn't work

### ISSUE THREAD

**Issue by tissole** [23rd/tdesktop#53]
### Steps to reproduce
1.User sets custom URI Scheme like this `potplayer://`
2. Then right-clicks on a Youtube link and selects Open link with URI Scheme

### Expected behaviour
Potplayer should play the YT video

### Actual behaviour
PotPlayer does not play the video

![Z0rXE0k8ic](https://user-images.githubusercontent.com/78413495/128887451-863c5853-8724-4414-bff3-9df155429b3f.png)

Same thing when setting `vlc://` as URI Scheme (the standalone application does not open, only the one installed from Microsoft Store)

![ApplicationFrameHost_beSk8TN4RC](https://user-images.githubusercontent.com/78413495/128887886-02ce31e6-7f6b-46ce-8904-54b3c4a4ef8d.png)

### Configuration
**Operating system:**
Windows 10 x64

**Version of Telegram Desktop:**
2.9

**Comment by 23rd** [comment]
Should be fixed in 2.9.2.

**Comment by tissole** [comment]
Yes, is working now. Thanks for the update! I tested with `potplayer://` and `mpv://`, both working. But is not working with VLC, no idea why. What is the URI scheme for MPC-BE?

**Comment by 23rd** [comment]
I'm not really sure that the standalone vlc even has an own uri scheme.
It depends on the developers.
