### ISSUE TITLE
[Question] Telegram channel file icons?

### ISSUE THREAD

**Issue by Sakujes** [23rd/tdesktop#54]
The official @Forkgram telegram channel is the only one I have ever seen to have files with icons on Telegram, and since it has no discussion group or other place to talk, I need to ask here:
How are the file icons added before they are uploaded to the Telegram channel? Is there any 3rd party tool able to do this to any file? I tried downloading the latest https://github.com/Forkgram/tdesktop/releases/download/v3.0.1/Telegram.zip and uploading that straight to Telegram, but it did not have the custom icon below:
![image](https://user-images.githubusercontent.com/64438637/132091249-c4023013-e6c6-4236-96f4-b8adaa895a90.png)

**Comment by 23rd** [comment]
This feature has always existed ([core.telegram.org/bots/api#senddocument](https://core.telegram.org/bots/api#senddocument)), but there is no UI for it.
