### ISSUE TITLE
[Feature request] Disable auto-submitting of the local passcode?

### ISSUE THREAD

**Issue by rgabbo** [23rd/tdesktop#57]
### Is your feature request related to a problem?

I noticed that the auto-submitting function slows down considerably the starting process while I type, compared with Telegram official client. Considering also that this feature is marked as experimental, it would be great in my opinion to add an option to disable this behavior

### Describe the solution you'd like

An option in "Fork setting" section to disable auto-submitting of the local passcode

### Describe alternatives you've considered

Fixing the lag but considering that is an experimental feature seems more a long term solution

**Comment by 23rd** [comment]
Okay, I'll bring a new setting for that in the next version.
