### ISSUE TITLE
app doesn't work

### ISSUE THREAD

**Issue by rzasharifi** [23rd/tdesktop#61]
### Steps to reproduce

Hi, I used beta version, I do not remember clearly but I watched a picture and try to save it but suddenly app crashed and it didn't work anymore. this happened before (crashing!) but it works after reboot app! 

### Expected behaviour

after click on app's icon, it works.

### Actual behaviour

it does not respond!

### Operating system

windows 10 enterprise ltsc /version 1809/ os build 17763.2366

### Version of Telegram Desktop

3.3.0.0

### Installation source

Other (unofficial) source

**Comment by rzasharifi** [comment]
what happens if I reinstall the app in same direction? will I loose my accounts?

**Comment by 23rd** [comment]
Your account is in the `tdata` directory.

**Comment by rzasharifi** [comment]
so what should I do for access my accounts again? (I don't access my numbers...)

**Comment by 23rd** [comment]
It may be too late, but I think I found and fixed the source of your problem.

**Comment by rzasharifi** [comment]
so what should I do after you fixed it! reinstall the program or move tdata folder to new app's version or what? </3

**Comment by 23rd** [comment]
Download the exe of the latest version and replace the old exe with the new one.

**Comment by rzasharifi** [comment]
thank you man. it's work now.
