### ISSUE TITLE
[Feature Request] Deal with annoying Emoji window popup

### ISSUE THREAD

**Issue by Volutar** [23rd/tdesktop#62]
There are plenty of feature requests of that thing in Telegram.
Thing is - annoying emoji popup when moving mouse near textbox. And this popup isn't hidden easily - it takes pause before disappearing when pointer moved off.

### Describe the solution you'd like

Disable hover popup at all. Consistent behavior for all icons.
Make left click open popup. Right click - enlarges window with Emoji panel (currently it's left-click behavior, and no right click behavior at all).

### Describe alternatives you've considered

Delay before popping up (like 0.3s or some configured value).

**Comment by 23rd** [comment]
You can check the latest version.

**Comment by Volutar** [comment]
Yeeeeeaa-a-ah!
Thank you very much! :)
