### ISSUE TITLE
Account limit extension broken

### ISSUE THREAD

**Issue by nift4** [23rd/tdesktop#65]
### Steps to reproduce

1. have more than 3 accounts before 4.0
2. update to 4.0
3. get annoyed by the popup

### Expected behaviour

No premium popup while switching accounts

### Actual behaviour

Premium popup while switching accounts

### Operating system

Debian testing, KDE

### Version of Telegram Desktop

4.0

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Is it better now?

**Comment by nift4** [comment]
Yep seems to be fixed now. Thanks
