### ISSUE TITLE
[Question] Linux binary release

### ISSUE THREAD

**Issue by figue** [23rd/tdesktop#66]
I saw the action for Linux was completed for the past few versions, but the tar.xz was not released. Can be pushed?

Thank you!

**Comment by 23rd** [comment]
Sorry. As a temporary workaround you can download v4.0.0, it will update to v4.0.2.

**Comment by figue** [comment]
Nothing to be sorry. This project is great. Thank you.

I have to apologize to not explain the root cause of my question. I posted it because I'm the maintainer of package [forkgram-bin](https://aur.archlinux.org/packages/forkgram-bin) in Archlinux AUR, which uses as source the Telegram.tar.xz posted in Releases. It seems that 4.0.2 is not available either. Can I grab the 4.0.2 binary from somewhere else?

As Forkgram is managed by a package, I disable the user update capability adding the binary in /etc/tdesktop/externalupdater. Because the binary path is only root writable and user has to build and install the package from AUR (the user repository) to have the latest version.

Thank you again

**Comment by 23rd** [comment]
The release binaries for Linux are built by CI, but sometimes something goes wrong and uploading of an asset to the Release page fails.
Today I had rerun the latest CI job and now v4.0.2 for Linux is in the Release page.

**Comment by figue** [comment]
Perfect. Thank you again!
