### ISSUE TITLE
[Question] Telegram PDB 

### ISSUE THREAD

**Issue by Keks1993** [23rd/tdesktop#67]
Hello. 
I'm trying to look into something and currently need to correlate the IDA Pro output and the source code.

I found a similar query here:
https://github.com/telegramdesktop/tdesktop/issues/9882
but it is no longer available.  Could you do the same for me (pdb file, with compiled exe)?

**Comment by 23rd** [comment]
Check this out.
github.com/23rd/tdesktop/actions/runs/2645231954

After 24h I'll delete the artifacts.

**Comment by ghost** [comment]
Thank you so math.
