### ISSUE TITLE
Archlinux 4.0.3 not compiled

### ISSUE THREAD

**Issue by ptr1337** [23rd/tdesktop#68]
### Steps to reproduce

```
git clone https://aur.archlinux.org/forkgram
cd forkgram
makepkg -si
```

### Expected behaviour

Should build correctly

### Actual behaviour

Compilation throws a error here:
`FAILED: Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/lottie/lottie_emoji.cpp.o 
/usr/lib/ccache/bin/c++ -DCRL_USE_COMMON_QUEUE -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION -DDESKTOP_APP_USE_PACKAGED -DLOTTIE_USE_CACHE -DLOT_BUILD -DQT_CORE_LIB -DQT_GUI_LIB -DQT_IMPLICIT_QCHAR_CONSTRUCTION -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_SVG_LIB -DQT_WIDGETS_LIB -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/SourceFiles -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_base -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_rpl -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_crl -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/build/Telegram/lib_ui/gen -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_ui -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_ui/emoji_suggestions -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/ThirdParty/rlottie/inc -isystem /usr/include/qt/QtCore/5.15.5 -isystem /usr/include/qt/QtCore/5.15.5/QtCore -isystem /usr/include/qt/QtGui/5.15.5 -isystem /usr/include/qt/QtGui/5.15.5/QtGui -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtSvg -isystem /usr/include/giomm-2.4 -isystem /usr/lib/giomm-2.4/include -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glibmm-2.4 -isystem /usr/lib/glibmm-2.4/include -isystem /usr/include/sigc++-2.0 -isystem /usr/lib/sigc++-2.0/include -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/ffmpeg4.4 -march=x86-64 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -mpclmul -ftree-slp-vectorize -fdata-sections -ffunction-sections -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -fstack-protector-all -fPIC -fno-strict-aliasing -pipe -Wall -Wextra -Wno-unused-parameter -Wno-switch -Wno-missing-field-initializers -Wno-sign-compare -Wno-deprecated -fstack-clash-protection -Wno-maybe-uninitialized -pthread -std=gnu++20 -MD -MT Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/lottie/lottie_emoji.cpp.o -MF Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/lottie/lottie_emoji.cpp.o.d -o Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/lottie/lottie_emoji.cpp.o -c /tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie/lottie/lottie_emoji.cpp
In file included from /tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie/lottie/lottie_emoji.cpp:7:
/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie/lottie/lottie_emoji.h:31:14: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   31 |         std::unique_ptr<rlottie::Animation> _rlottie;
      |              ^~~~~~~~~~
/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie/lottie/lottie_emoji.h:12:1: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
   11 | #include <QtGui/QImage>
  +++ |+#include <memory>
   12 | `
   
   Compiled in a chroot

### Operating system

Archlinux

### Version of Telegram Desktop

4.0.3

### Installation source

Other (unofficial) source

### Logs

```shell
FAILED: Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/lottie/lottie_emoji.cpp.o 
/usr/lib/ccache/bin/c++ -DCRL_USE_COMMON_QUEUE -DDESKTOP_APP_DISABLE_CRASH_REPORTS -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION -DDESKTOP_APP_USE_PACKAGED -DLOTTIE_USE_CACHE -DLOT_BUILD -DQT_CORE_LIB -DQT_GUI_LIB -DQT_IMPLICIT_QCHAR_CONSTRUCTION -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_SVG_LIB -DQT_WIDGETS_LIB -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/SourceFiles -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_base -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_rpl -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_crl -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/build/Telegram/lib_ui/gen -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_ui -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_ui/emoji_suggestions -I/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/ThirdParty/rlottie/inc -isystem /usr/include/qt/QtCore/5.15.5 -isystem /usr/include/qt/QtCore/5.15.5/QtCore -isystem /usr/include/qt/QtGui/5.15.5 -isystem /usr/include/qt/QtGui/5.15.5/QtGui -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtSvg -isystem /usr/include/giomm-2.4 -isystem /usr/lib/giomm-2.4/include -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glibmm-2.4 -isystem /usr/lib/glibmm-2.4/include -isystem /usr/include/sigc++-2.0 -isystem /usr/lib/sigc++-2.0/include -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/ffmpeg4.4 -march=x86-64 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -mpclmul -ftree-slp-vectorize -fdata-sections -ffunction-sections -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -fstack-protector-all -fPIC -fno-strict-aliasing -pipe -Wall -Wextra -Wno-unused-parameter -Wno-switch -Wno-missing-field-initializers -Wno-sign-compare -Wno-deprecated -fstack-clash-protection -Wno-maybe-uninitialized -pthread -std=gnu++20 -MD -MT Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/lottie/lottie_emoji.cpp.o -MF Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/lottie/lottie_emoji.cpp.o.d -o Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/lottie/lottie_emoji.cpp.o -c /tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie/lottie/lottie_emoji.cpp
In file included from /tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie/lottie/lottie_emoji.cpp:7:
/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie/lottie/lottie_emoji.h:31:14: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   31 |         std::unique_ptr<rlottie::Animation> _rlottie;
      |              ^~~~~~~~~~
/tmp/makepkg/forkgram/src/frk-v4.0.3-full/Telegram/lib_lottie/lottie/lottie_emoji.h:12:1: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
   11 | #include <QtGui/QImage>
  +++ |+#include <memory>
   12 |
```

**Comment by 23rd** [comment]
`git clone --recursive`?

**Comment by ptr1337** [comment]
> `git clone --recursive`?

It is pulling your 4.0.3 release

**Comment by 23rd** [comment]
Then I dunno. =(
The version for LInux dropped support of Qt5.

**Comment by ptr1337** [comment]
> Then I dunno. =( The version for LInux dropped support of Qt5.

So, it will need qt6? I will test it

**Comment by ptr1337** [comment]
I have found the issue.
Its solved. I will update the aur package
