### ISSUE TITLE
[Feature Request] A toggle or an option to disable mentioning users/bots in chats by the name

### ISSUE THREAD

**Issue by rkn45** [23rd/tdesktop#71]
### Is your feature request related to a problem?

Inline bots become unusable when you tab-complete or use the tool-tip to select the usernames, as the client defaults to mentioning by name, instead of the username. 

### Describe the solution you'd like

Making an option or a toggle in settings to disable/enable such a feature might be one of the easier solutions. 
The other possible solution may perhaps be to make name-mentions differentiate between actual users or inline bots.

### Describe alternatives you've considered

As an alternative I just type in inline bot usernames manually, by hand. Although it is not hard to do, an option to toggle name mentioning would be appreciated. Thanks.

**Comment by 23rd** [comment]
You can hold `Ctrl`.

**Comment by rkn45** [comment]
> You can hold `Ctrl`.

Thank you for giving an another alternative, but still, an option to toggle this feature would've been good to have.
