### ISSUE TITLE
[Question] Windows x64 Release build linker failure

### ISSUE THREAD

**Issue by rkn45** [23rd/tdesktop#80]
Hello.

I was trying to build Forkgram v4.3.3 for win x64 with some stuff regarding image size limit for compressing fixed, from the source, included in the release, but encountered some problems. To be specific, when building "Telegram" VS project against a "Release" config, the build fails at the very end with linker complaining about unresolved external symbols (see build log snippet below). Where does the problem lie, and how can I fix it?

P.S. I'm using Visual Studio Community 2022 v15.4.1 on Windows 10 (Build 19045.2251). Also, everything builds fine when building for Debug.

`48>   Creating library C:/Users/anus/Desktop/tdesktop/frksrc/out/Telegram/Release/Telegram.lib and object C:/Users/anus/Desktop/tdesktop/frksrc/out/Telegram/Release/Telegram.exp`
`48>uri_open.obj : error LNK2019: unresolved external symbol "public: __cdecl winrt::Windows::Foundation::Uri::Uri(struct winrt::param::hstring const &)" (??0Uri@Foundation@Windows@winrt@@QEAA@AEBUhstring@param@3@@Z) referenced in function "void __cdecl Forkgram::OpenUrlWithCustomUri(class QString const &)" (?OpenUrlWithCustomUri@Forkgram@@YAXAEBVQString@@@Z)`
`48>C:\Users\anus\Desktop\tdesktop\frksrc\out\Release\Telegram.exe : fatal error LNK1120: 1 unresolved externals`
`48>Done building project "Telegram.vcxproj" -- FAILED.`

**Comment by 23rd** [comment]
You can try to add this line to the `uri_open.cpp` file.
```
#include <winrt/Windows.Foundation.h>
```

**Comment by rkn45** [comment]
Thanks, after adding that line, Forkgram finally was able to be built for Release correctly. Closing the issue.
