### ISSUE TITLE
crash when answer android video call

### ISSUE THREAD

**Issue by Aokromes** [23rd/tdesktop#86]
### Steps to reproduce

answer video call made by someone using android telegram.
crash

### Expected behaviour

no crash :)

### Actual behaviour

it crashes as soon a video call made from android is answered

### Operating system

windows 10

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
still crashes on 4.5.5

https://mega.nz/file/52JCGQwJ#Do6Uw3IF8mDWO-vtvPWUUD9i0JsdXsCK4dqXEEFdxVE

since crash uploader fails.

**Comment by 23rd** [comment]
Should be fixed now.

**Comment by Aokromes** [comment]
confirmed.

**Comment by Xiaoia8** [comment]
Still crashes on v4.8.1

**Comment by Aokromes** [comment]
cannot reproduce on 4.8.3.
if it's crashing for you enable beta and restart telegram and when you have a crash open a new ticket with the crash id.
