### ISSUE TITLE
[Feature Request] .tar.xz Releases ?

### ISSUE THREAD

**Issue by garfieldairlines** [23rd/tdesktop#88]
### Is your feature request related to a problem?

Hello, it has been a while that the .tar.xz releases are missing, could you please please fix it ? I would love to update my client on Linux.

Thank you very much.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by mckaygerhard** [comment]
wel @garfieldairlines  seems this are windoser focused project.. also if there are some static compilation will be agains new glibc so will work only in pretty few linuxes.. 

noted at lesat we have full source code so we can build it by ourselft

**Comment by 23rd** [comment]
Should be better now.

**Comment by garfieldairlines** [comment]
Indeed, thanks !
