### ISSUE TITLE
Win32-bit builds , please ! [Feature Request] 

### ISSUE THREAD

**Issue by DI555** [23rd/tdesktop#94]
### Is your feature request related to a problem?

not possible to run on 32-bit win systems :"((

### Describe the solution you'd like

please, provide and 32-bit builds also!
we have a lots of win7-32bit oses yet..

### Describe alternatives you've considered

official tg repo is not a case, forkgram is much better!

**Comment by 23rd** [comment]
Oh, I was hoping no one would need 32 bit builds anymore. I've uploaded a 32 bit build to the current latest release, and will hopefully do so periodically for future releases in the future. Auto-update builds are not planned.

**Comment by DI555** [comment]
Great news!
not only lots of my win7-32 macheenes and i thank you, but and ReactOS, a win32-compatible(still 32bit) os, also too !!!
╰(▔∀▔)╯

**Comment by 23rd** [comment]
Updated the latest version.
