### ISSUE TITLE
[Feature Request] Export restricted content chats

### ISSUE THREAD

**Issue by thisago** [23rd/tdesktop#99]
### Is your feature request related to a problem?

no, just the issue that I can't export restrict chats

### Describe the solution you'd like

It will be awesome if the export chat button be available in chates where "restrict saving content" is on.
I tried to edit the source but for some reason the build never succeeds (I asked in TG chats and looks like that my PC haven't enough RAM)

### Describe alternatives you've considered

I think that just removing the verification it will work, because all data is shown normally in this chats, but the app blocks download

**Comment by 23rd** [comment]
> I tried to edit the source but for some reason the build never succeeds (I asked in TG chats and looks like that my PC haven't enough RAM)

You can fork a repository, open the `tdesktop/.github/workflows/win.yml` file, change the `UPLOAD_ARTIFACT ` property from `false` to `true`, commit this change and push it to your fork. Then after couple of hours you will be able to find your own `Telegram.exe` binary in the `artifacts` subcategory from the `Actions` tab.

**Comment by thisago** [comment]
@23rd Thank you, I'il try
